const endpoints = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    session: "/auth/session",
  },
  systemAnnouncements: {
    current: "/system-announcements/current",
    list: "/system-announcements",
    end: (id) => `/system-announcements/${id}/end`,
  },
  users: {
    list: "/users",
    byId: (id) => `/users/${id}`,
  },
  dashboard: {
    monthly: "/dashboard/monthly",
  },
  employees: {
    list: "/employees",
    create: "/employees",
  },
  catalog: {
    branches: "/catalog/branches",
    customers: "/catalog/customers",
    products: "/catalog/products",
    productById: (id) => `/catalog/products/${id}`,
    productYield: (id) => `/catalog/products/${id}/yield`,
    rawMaterials: "/catalog/raw-materials",
    rawMaterialById: (id) => `/catalog/raw-materials/${id}`,
    rawMaterialStatus: (id) => `/catalog/raw-materials/${id}/status`,
    taxRates: "/catalog/tax-rates",
    productCategories: "/catalog/product-categories",
    productCategoryById: (id) => `/catalog/product-categories/${id}`,
    rawMaterialCategories: "/catalog/raw-material-categories",
    suppliers: "/catalog/suppliers",
  },
  commercial: {
    customers: "/commercial/customers",
    customerById: (id) => `/commercial/customers/${id}`,
    customerStatus: (id) => `/commercial/customers/${id}/status`,
    customerAssignments: "/commercial/customer-assignments",
    customerAssignment: (id) => `/commercial/customer-assignments/${id}`,
  },
  orders: {
    list: "/orders",
    baseData: "/orders/base-data",
    salesSettings: "/orders/settings/sales",
    create: "/orders",
    items: (id) => `/orders/${id}/items`,
    printData: (id) => `/orders/${id}/print-data`,
    confirmPrint: (id) => `/orders/${id}/confirm-print`,
    upsertItem: (id) => `/orders/${id}/items`,
    confirm: (id) => `/orders/${id}/confirm`,
    cancel: (id) => `/orders/${id}/cancel`,
    dispatch: (id) => `/orders/${id}/dispatch`,
    deliver: (id) => `/orders/${id}/deliver`,
    deliveryDate: (id) => `/orders/${id}/delivery-date`,
    commissions: "/orders/commissions",
    dailySettlement: "/orders/commissions/daily-settlement",
    gifts: "/orders/gifts",
    customerCredit: (customerId) => `/orders/customer-credits/${customerId}`,
    sellerCustomerAssignments: "/orders/seller-customer-assignments",
    sellerCustomerAssignment: (customerId) => `/orders/seller-customer-assignments/${customerId}`,
    sellerCustomerPortfolio: (sellerId) => `/orders/seller-customer-assignments/seller/${sellerId}`,
    returns: "/orders/returns",
    returnOptions: "/orders/returns/options",
    authorizeReturn: (id) => `/orders/returns/${id}/authorize`,
    rejectReturn: (id) => `/orders/returns/${id}/reject`,
    createProduction: (id) => `/orders/${id}/create-production`,
    productionReservations: (id) => `/orders/${id}/production-reservations`,
    productionReservationOptions: (id) => `/orders/${id}/production-reservation-options`,
    deliverProductionReservation: (id) => `/orders/production-reservations/${id}/deliver`,
    releaseProductionReservation: (id) => `/orders/production-reservations/${id}/release`,
    purchaseOrders: "/orders/purchase-orders",
    pendingPurchaseOrders: "/orders/purchase-orders/pending",
    purchaseOrderHistory: "/orders/purchase-orders/history",
    purchaseOrderDetail: (id) => `/orders/purchase-orders/${id}/detail`,
    receivePurchaseOrder: (id) => `/orders/purchase-orders/${id}/receive`,
  },
  production: {
    orders: "/production/orders",
    baseData: "/production/base-data",
    results: "/production/results",
    batches: "/production/batches",
    pendingPackaging: "/production/packaging/pending",
    packagingPackers: "/production/packaging/packers",
    packingReports: "/production/packaging/reports",
    justifiedShortages: "/production/packaging/shortages",
    damages: "/production/damages",
    dayReport: "/production/reports/day",
    monthReport: "/production/reports/month",
    rawMaterialUsageReport: "/production/reports/raw-material-usage",
    rawMaterialUsageByProductReport: "/production/reports/raw-material-usage-by-product",
    packingSummaryReport: "/production/reports/packing-summary",
    plans: "/production/plans",
    planById: (id) => `/production/plans/${id}`,
    myPlans: "/production/my-plans",
    myBaseData: "/production/my-base-data",
    myBatches: "/production/my-batches",
    startPlanItem: (id) => `/production/plans/items/${id}/start`,
    finishPlanItem: (id) => `/production/plans/items/${id}/finish`,
    startPlanProduct: (id) => `/production/plans/products/${id}/start`,
    planProductProgress: (id) => `/production/plans/products/${id}/progress`,
    skipPlanProduct: (id) => `/production/plans/products/${id}/skip`,
    finishPlanProduct: (id) => `/production/plans/products/${id}/finish`,
    correctPlanProduct: (id) => `/production/plans/products/${id}/correction`,
    notifications: "/production/notifications",
    notificationViewed: (id) => `/production/notifications/${id}/viewed`,
    orderItems: (id) => `/production/orders/${id}/items`,
    orderItem: (id, itemId) => `/production/orders/${id}/items/${itemId}`,
    cancelOrderItem: (id, itemId) => `/production/orders/${id}/items/${itemId}/cancel`,
    orderItemResults: (id, itemId) => `/production/orders/${id}/items/${itemId}/results`,
    closeOrder: (id) => `/production/orders/${id}/close`,
    cancelOrder: (id) => `/production/orders/${id}/cancel`,
  },
  recipes: {
    list: "/recipes",
    byId: (id) => `/recipes/${id}`,
    version: (id) => `/recipes/${id}/version`,
    baseData: "/recipes/base-data",
    costing: "/recipes/costing",
    outputs: (id) => `/recipes/${id}/outputs`,
    output: (id, productId) => `/recipes/${id}/outputs/${productId}`,
  },
  inventory: {
    baseData: "/inventory/base-data",
    movements: "/inventory/movements",
  },
  reports: {
    audit: "/reports/audit",
  },
  settings: {
    posTicket: "/settings/pos-ticket",
  },
  adminAuth: {
    users: "/admin-auth/users",
    userProfile: (id) => `/admin-auth/users/${id}/profile`,
    userRoles: (id) => `/admin-auth/users/${id}/roles`,
    userStatus: (id) => `/admin-auth/users/${id}/status`,
    userForcePasswordReset: (id) => `/admin-auth/users/${id}/force-password-reset`,
    userLogoutAll: (id) => `/admin-auth/users/${id}/logout-all`,
    userResetPassword: (id) => `/admin-auth/users/${id}/reset-password`,
    changePassword: "/admin-auth/change-password",
  },
  rbac: {
    roles: "/rbac/roles",
    roleById: (id) => `/rbac/roles/${id}`,
    rolePermissions: (id) => `/rbac/roles/${id}/permissions`,
    permissions: "/rbac/permissions",
    viewAccessUsers: "/rbac/view-access/users",
    userPermissions: (id) => `/rbac/users/${id}/permissions`,
  },
};

export default endpoints;






