const endpoints = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
  },
  users: {
    list: "/users",
    byId: (id) => `/users/${id}`,
  },
  catalog: {
    branches: "/catalog/branches",
    customers: "/catalog/customers",
    routes: "/catalog/routes",
    products: "/catalog/products",
    rawMaterials: "/catalog/raw-materials",
    taxRates: "/catalog/tax-rates",
    productCategories: "/catalog/product-categories",
    rawMaterialCategories: "/catalog/raw-material-categories",
    suppliers: "/catalog/suppliers",
  },
  commercial: {
    customers: "/commercial/customers",
    customerById: (id) => `/commercial/customers/${id}`,
    customerStatus: (id) => `/commercial/customers/${id}/status`,
    routes: "/commercial/routes",
    routeById: (id) => `/commercial/routes/${id}`,
    routeStatus: (id) => `/commercial/routes/${id}/status`,
    assignRouteDriver: (id) => `/commercial/routes/${id}/assign-driver`,
  },
  orders: {
    list: "/orders",
    baseData: "/orders/base-data",
    create: "/orders",
    items: (id) => `/orders/${id}/items`,
    upsertItem: (id) => `/orders/${id}/items`,
    confirm: (id) => `/orders/${id}/confirm`,
    cancel: (id) => `/orders/${id}/cancel`,
    dispatch: (id) => `/orders/${id}/dispatch`,
    createProduction: (id) => `/orders/${id}/create-production`,
    purchaseOrders: "/orders/purchase-orders",
    pendingPurchaseOrders: "/orders/purchase-orders/pending",
    receivePurchaseOrder: (id) => `/orders/purchase-orders/${id}/receive`,
  },
  production: {
    orders: "/production/orders",
    baseData: "/production/base-data",
    results: "/production/results",
    orderItems: (id) => `/production/orders/${id}/items`,
    orderItem: (id, itemId) => `/production/orders/${id}/items/${itemId}`,
    cancelOrderItem: (id, itemId) => `/production/orders/${id}/items/${itemId}/cancel`,
    orderItemResults: (id, itemId) => `/production/orders/${id}/items/${itemId}/results`,
    closeOrder: (id) => `/production/orders/${id}/close`,
    cancelOrder: (id) => `/production/orders/${id}/cancel`,
  },
  recipes: {
    list: "/recipes",
    baseData: "/recipes/base-data",
  },
  inventory: {
    baseData: "/inventory/base-data",
    movements: "/inventory/movements",
  },
  reports: {
    audit: "/reports/audit",
  },
  adminAuth: {
    users: "/admin-auth/users",
    userProfile: (id) => `/admin-auth/users/${id}/profile`,
    userRoles: (id) => `/admin-auth/users/${id}/roles`,
    userStatus: (id) => `/admin-auth/users/${id}/status`,
    userForcePasswordReset: (id) => `/admin-auth/users/${id}/force-password-reset`,
    userLogoutAll: (id) => `/admin-auth/users/${id}/logout-all`,
    userResetPassword: (id) => `/admin-auth/users/${id}/reset-password`,
    changePassword: "/admin-auth/change-password",
  },
  rbac: {
    roles: "/rbac/roles",
    roleById: (id) => `/rbac/roles/${id}`,
    rolePermissions: (id) => `/rbac/roles/${id}/permissions`,
    permissions: "/rbac/permissions",
  },
};

export default endpoints;
